name: Continuous integration
on: [ push, pull_request ]

# TODO: fix tests on x86_64-linux, run cargo test + cargo taurpaulin + codecov upload.

env:
  BINDGEN_EXTRA_CLANG_ARGS: -B/usr/include/

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
          - 1.60.0  # MSRV

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions/cache@v3
        with:
          path: |
                target/xtask/
          key: ${{ runner.os }}-xtask

      - run: sudo apt-get install -y avr-libc tar wget

      - name: Install `arm-frc2022-unknown-gcc` toolchain.
        run: wget https://github.com/wpilibsuite/roborio-toolchain/releases/download/v2022-1/FRC-2022-Linux-Toolchain-7.3.0.tar.gz && tar -xzvf FRC-2022-Linux-*.tar.gz && echo "$(pwd)/frc2022/roborio/bin/" >> $GITHUB_PATH

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy
          target: arm-unknown-linux-gnueabi

      - uses: actions-rs/cargo@v1
        with:
          command: run
          args: -p xtask -- init

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target arm-unknown-linux-gnueabi

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
